export const GETQUESTIONSUCCESS = "GETQUESTIONSUCCESS"
export const GETQUESTIONREQUEST = "GETQUESTIONREQUEST"
export const GETQUESTIONFALIUR = "GETQUESTIONFALIUR"
export const GETSINGLEQUESTION  = "GETSINGLEQUESTION" ;
